### ISSUE TITLE
Can't not make component and container

### ISSUE THREAD

**Issue by Lana-Banana** [joshjg/vscode-generate-react-component#5]
It was making react component very well until about 2 weeks ago.
But, today, I can't generate react component and container using this plug-in.

My Environment is..
VScode version: 1.31.1
Node.js: 10.2.0

VScode development tool's console output is... 
---------------------------------------------------------------------------------
mainThreadExtensionService.ts:46 [[object Object]]Callback must be a function
e.$onExtensionRuntimeError @ mainThreadExtensionService.ts:46
mainThreadExtensionService.ts:47 TypeError [ERR_INVALID_CALLBACK]: Callback must be a function
	at maybeCallback (fs.js:157:9)
	at Object.fs.appendFile (fs.js:1344:14)
	at fs.mkdir.fs.readdir.files.map.fs.readFile (c:\Users\SDS\.vscode\extensions\joshjg.generate-react-component-0.2.1\extension.js:56:14)
	at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:440:3)
e.$onExtensionRuntimeError @ mainThreadExtensionService.ts:47
mainThreadExtensionService.ts:46 [[object Object]]Callback must be a function
e.$onExtensionRuntimeError @ mainThreadExtensionService.ts:46
mainThreadExtensionService.ts:47 TypeError [ERR_INVALID_CALLBACK]: Callback must be a function
	at maybeCallback (fs.js:157:9)
	at Object.fs.appendFile (fs.js:1344:14)
	at fs.mkdir.fs.readdir.files.map.fs.readFile (c:\Users\SDS\.vscode\extensions\joshjg.generate-react-component-0.2.1\extension.js:56:14)
	at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:440:3)
e.$onExtensionRuntimeError @ mainThreadExtensionService.ts:47
mainThreadExtensionService.ts:46 [[object Object]]Callback must be a function
e.$onExtensionRuntimeError @ mainThreadExtensionService.ts:46
mainThreadExtensionService.ts:47 TypeError [ERR_INVALID_CALLBACK]: Callback must be a function
	at maybeCallback (fs.js:157:9)
	at Object.fs.appendFile (fs.js:1344:14)
	at fs.mkdir.fs.readdir.files.map.fs.readFile (c:\Users\SDS\.vscode\extensions\joshjg.generate-react-component-0.2.1\extension.js:56:14)
	at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:440:3)
e.$onExtensionRuntimeError @ mainThreadExtensionService.ts:47
9console.ts:134 [Extension Host] (electron) The 'lstatSyncNoException' function has been deprecated and marked for removal.

**Comment by boxer042** [comment]
same issue too,

**Comment by c094728** [comment]
Same issue too

**Comment by ghost** [comment]
Same issue
